version: '3'
services:
  AWS_DOCKER:          
    image: jupyter/base-notebook
    container_name: jupyter-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./AWS_HW:/home/jovyan/work/
    command: start-notebook.sh --NotebookApp.token=''
